"""Tests for `hybrid_agent.task_generator` post-processing helpers.

We don't test the LLM call itself (that's mocked in CLI integration tests
elsewhere). We focus on the deterministic text transforms that have caused
real bugs — fence stripping and the duplicate-task-section dedupe.
"""
from __future__ import annotations

import logging

from hybrid_agent.task_generator import _dedupe_task_sections, _strip_wrapper_fences


# ---------------------------------------------------------------------------
# _strip_wrapper_fences
# ---------------------------------------------------------------------------

class TestStripWrapperFences:
    def test_no_fence_passes_through(self):
        text = "# Task: T001 — Foo\nbody\n"
        assert _strip_wrapper_fences(text) == text

    def test_strips_outer_markdown_fence(self):
        text = "```markdown\n# Task: T001 — Foo\nbody\n```"
        out = _strip_wrapper_fences(text)
        assert out.startswith("# Task: T001")
        assert "```" not in out

    def test_inner_fences_preserved(self):
        text = "# Task: T001 — Foo\n\n```python\ncode block\n```\n"
        # No outer fence, so inner block must survive untouched
        assert "```python" in _strip_wrapper_fences(text)


# ---------------------------------------------------------------------------
# _dedupe_task_sections
# ---------------------------------------------------------------------------

ONE_TASK = """\
# Task: T001 — Foo
- depends_on:
- tags: x
- complexity: low
body line
"""

TWO_TASKS = """\
# Task: T001 — Foo
- depends_on:
body A

# Task: T002 — Bar
- depends_on: T001
body B
"""


class TestDedupeTaskSections:
    def test_no_duplicates_unchanged(self):
        assert _dedupe_task_sections(TWO_TASKS).strip() == TWO_TASKS.strip()

    def test_no_task_headers_returned_as_is(self):
        text = "Just a paragraph\n\nWith no headers.\n"
        assert _dedupe_task_sections(text) == text

    def test_drops_full_repeat(self, caplog):
        """The exact failure mode from the user log: 17 tasks emitted twice.
        The first 17 are kept, the last 17 dropped."""
        doubled = TWO_TASKS + "\n" + TWO_TASKS
        with caplog.at_level(logging.WARNING):
            out = _dedupe_task_sections(doubled)
        # Each id should appear exactly once now
        assert out.count("# Task: T001") == 1
        assert out.count("# Task: T002") == 1
        # Warning logged
        assert any("duplicate" in rec.message.lower() for rec in caplog.records)

    def test_keeps_first_occurrence_when_bodies_differ(self):
        """If the model writes two T001 sections with different bodies, we
        deterministically keep the first one."""
        text = (
            "# Task: T001 — Foo\nfirst body\n\n"
            "# Task: T001 — Foo (rewrite)\nsecond body\n"
        )
        out = _dedupe_task_sections(text)
        assert "first body" in out
        assert "second body" not in out

    def test_partial_duplicate(self, caplog):
        """Repeating only some tasks (T001 twice, T002 once)."""
        text = (
            "# Task: T001 — Foo\nbody A\n\n"
            "# Task: T002 — Bar\nbody B\n\n"
            "# Task: T001 — Foo\nbody A duplicate\n"
        )
        with caplog.at_level(logging.WARNING):
            out = _dedupe_task_sections(text)
        assert out.count("# Task: T001") == 1
        assert out.count("# Task: T002") == 1
        assert any("T001" in rec.message for rec in caplog.records)

    def test_preserves_preamble(self):
        """Lines before the first header (e.g. a preface comment) are kept."""
        text = "# Project plan\n\nGenerated by Claude.\n\n" + ONE_TASK
        out = _dedupe_task_sections(text)
        assert out.startswith("# Project plan")
        assert "# Task: T001" in out

    def test_handles_em_dash_and_colon_separators(self):
        """The header regex accepts ':', '-', '—', '–' between Task and id."""
        for sep in (":", "-", "—", "–"):
            text = f"# Task{sep} T001 — Foo\nbody\n\n# Task{sep} T001 — Foo\ndup\n"
            out = _dedupe_task_sections(text)
            # After dedup, exactly one T001 section should remain regardless of separator.
            assert out.count("T001") == 1, f"separator {sep!r} not recognised"

    def test_id_with_dot_or_underscore_handled(self):
        text = "# Task: T_01.a — X\nbody\n\n# Task: T_01.a — X\ndup\n"
        out = _dedupe_task_sections(text)
        assert out.count("T_01.a") <= 2  # Once in header, optionally once if title repeats id

    def test_trailing_newline_normalised(self):
        # Output should end with exactly one newline so the markdown parser
        # doesn't drop the last line.
        text = "# Task: T001 — Foo\nbody"  # no trailing newline
        out = _dedupe_task_sections(text)
        assert out.endswith("\n")
